services:
  payload:
    build: .
    volumes:
      - media:/app/media
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  media:
  data:
